[project]
name = "my_agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dependency-injector>=4.48.2",
    "pydantic-ai>=1.9.1",
    "pydantic-ai-slim[duckduckgo,mcp]>=1.9.1",
]
